### ISSUE TITLE
Figure out how it should work

### ISSUE THREAD

**Issue by MisterFruits** [yorickvanzweeden/android-ci#3]
I'm really interested with your mechanism that allow running android connect tests on CI (it's heartbreaking to see implemented tests not running). 

Problem is I'm pretty new to android/docker programmation and I can't get your script running on my public Gitlab account:

I gathered all your ci scrip in one (just correcting the location of the `android-wait-for-emulator`):

``` yaml
test:instrumented:debug:
  image: yorickvanzweeden/android-ci:latest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./gradlew
  stage: test
  only:
    - 18-follow-up-on-running-ui-tests-on-gitlab-ci
  script:
    # Running emulator
    - /sdk/emulator/emulator -avd ${AVD_NAME} -no-window -no-audio -snapshot ${SNAPSHOT_NAME} &

    # Wait for emulator
    - /android-wait-for-emulator

    # Run instrumented Android tests
    - /sdk/platform-tools/adb shell input keyevent 82
    - ./gradlew cAT
```

But I still face the error

```
emulator: ERROR: x86_64 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: KVM requires a CPU that supports vmx or svm
Waiting for emulator to start
No emulators were found
```
 
Can you say what did I do wrong ? I also saw !2 would you recommend basing my work on this branch ?

Cheers
